apiVersion: v1
kind: Pod
metadata:
  name: posts
spec:
  containers:
    - name: posts
      image: rfpc/posts:0.0.1
      imagePullPolicy: Never

      # REMEMBER TO ALWAYS ADD IMAGES TO THE DOCKER HUB! (docker push image)